### ISSUE TITLE
Issue with 'n_excl'

### ISSUE THREAD

**Issue by manferdinig** [s3alfisc/pyfixest#228]
Hi, many thanks for developing this. I am trying to run an FE regression on a large unabalanced panel. However, I keep getting the same error:

KeyError: 'n_excl'

Do you have any idea where this is coming from?

**Comment by s3alfisc** [comment]
Hi! Thanks for reaching out and reporting - I think this is the first "real" bug issue I get, so that's very cool 😀 

This is part of the [multicollinearity checks](https://github.com/s3alfisc/pyfixest/blob/c9cb184b34333c82cb11bec9e73e387efd63c170/pyfixest/feols.py#L1195) that pyfixest does and during which it drops multicollinear variables. 

Can you maybe provide me with a reproducible example? If you cannot / don't want to share your data publicly, maybe it would be ok to send it to me by email? 

Best, Alex

**Comment by s3alfisc** [comment]
Hi @manferdinig, just checking in - did you manage to fix this issue?

**Comment by s3alfisc** [comment]
Ok, this happens when`Feols` removes all variables because of multicollinearity. Maybe you misspecified your model? E.g. see this: 

```py
from pyfixest.estimation import feols
from pyfixest.utils import get_data
data = get_data()

fit = feols("Y ~ f1 | f1", data = data)
```
produces `KeyError: 'n_excl'`. 

In the dev branch, I now return a proper error message in case this happens =)
