### ISSUE TITLE
Collinearity checking bug in FEIV

### ISSUE THREAD

**Issue by jiafengkevinchen** [s3alfisc/pyfixest#236]
I think this line presumes that the IV model is just-identified. I get a dimension error when the system is over-identified. 
https://github.com/s3alfisc/pyfixest/blob/c9cb184b34333c82cb11bec9e73e387efd63c170/pyfixest/feiv.py#L42C1-L43C1
`len(self._collin_index)` is 1 + dim(exogenous covariates) whereas the dimension of `Z` should be dim(exogenous instruments) + dim(exogenous covariates)

A hacky but working solution is to pad `self._collin_index` with `False`s if the model is overidentified
```python
if self._collin_index is not None:
    # TODO: this does not implement collinearity checking for the instruments
    collin_index_z = np.array([False] * (Z.shape[1] - len(self._collin_index)) + list(self._collin_index))
    self._Z = Z[:, ~collin_index_z]
```
I imagine something goes wrong if the instruments are collinear though.

**Comment by s3alfisc** [comment]
Hi @jiafengkevinchen - thanks for reporting this! This is yet another bug.

 Here is what I think happens: the multicollinearity check is based on the set of exogenous regressors X and produces `self._collin_index`, which is a boolean of length `X.shape[1]`. Z is equal to the instrumental variables plus X, i.e. Z = [I, Z]. For just identified models, `X.shape[1] = Z.shape[1]`, but with more than one instruments, this of course no longer holds and ´Z[:, ~collin_index_z]´ should produce a dimensionality error. So I think that I simply need to conduct the multi col check for IVs based on Z instead of X. 

I am currently struggling with my local setup and R / Python interoperatibility but am hopeful that I can still fix this by the end of the day. 

Best, Alex

**Comment by s3alfisc** [comment]
Just for reference, here is a reproducible example: 

```py
from pyfixest.estimation import feols
from pyfixest.utils import get_data 
data = get_data()

fit = feols("Y ~ f1 | f1 | X1 ~ Z1 + Z2 ", data=data)
#            The following variables are collinear: ['f1'].
#            The variables are dropped from the model.
```
produces the following error: 

```py
IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 2
```

**Comment by s3alfisc** [comment]
I have added another collinearity check for `Feiv` [here](https://github.com/s3alfisc/pyfixest/blob/726037b8e9f9fa9f879bcdeb1bd0e4f44f5f8277/pyfixest/feiv.py#L45). You should be able to install the newest version `0.11.4` git by running 

```
pip install git+https://github.com/s3alfisc/pyfixest.git
```

I will wait a little longer with a new `PyPi` release as there are some additional bugs I want to tackle, and I also have some new features in the dev branch. 

Typing this, I just saw that you've found another issue, so there we go 😄

**Comment by jiafengkevinchen** [comment]
Thank you!
