### ISSUE TITLE
cold start problem in fixed effects specifications

### ISSUE THREAD

**Issue by apoorvalal** [s3alfisc/pyfixest#284]
Hi Alex, great work on the package.

I noticed some puzzling cold-start problems recently and figured it'd be worth flagging. Running a fixed effects regression for the first time seems to be oddly slow (presumably because of initializing cost for the numba stuff in the background?), while the same regression run with Formulaic's `C()` notation does not have this problem.

![image](https://github.com/s3alfisc/pyfixest/assets/12086926/43f5e55e-b743-484e-8b5e-4063c1ea567b)

I'm running pyfixest in a conda environment running python 3.11 on linux 22.04 LTS.

**Comment by s3alfisc** [comment]
Hi @apoorvalal - thanks for flagging this! 

I think this is indeed mostly `numba` JIT compiling the first run. There are two differences between the first and second specification of the model - in the first one, `feols()` is asked to demean `Y` and `X1` by `f1` prior to solving the normal equation, and this all happens in [numba](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/demean.py#L165). In the second specification, `formulaic` creates the fully one-hot encoded design matrix including all levels of `f1`, and there is no demeaning. The second difference relates to **standard error defaults** - whenever there's a fixed effect specified behind the `|` bar, the `fixest` default is to cluster by it - here by `f1`. The method to compute `CRV1` inference is also [implemented in numba ](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/feols.py#L1676) as it turned out to be a major performance bottleneck whenever the fixed effect / clustering variable is very high dimensional. `fit2` instead reports `iid` standard errors. This is not properly documented so I opened an issue for it https://github.com/s3alfisc/pyfixest/issues/285, thanks! 

In general I noticed there is quite the variance in JIT compilation time, sometimes `numba` compiles for much longer (up to 10, 20 seconds on the first run) - maybe you know more about this @styfenschaer: when running a `numba` function for the first time, does the compilation time is in any way impacted by the "complexity" of the numerical problem it is asked to solve? Where does the variance in compilation time that I observe (and maybe @apoorvalal as well) stem from?

**Comment by styfenschaer** [comment]
Hello @s3alfisc 

Runtime information should not matter. However, there are some cases where the same function can have very different compile times due to compile time information. For example, if certain branches of the program can be pruned based on variable values that are known at compile time (literal values). The compilation time can also vary greatly if large tuples are passed to the function. Although this appears to be runtime information, it is actually not. The length of a tuple must be known to Numba at compile time. I can't remember if this is the case with any function that `pyfixest` uses. You can see what I mean by running this code:
```
import numba as nb 
import numpy as np

# initialize numba
nb.njit(lambda: None)()

@nb.njit 
def foo(t):
    pass

t0 = (0,) * 1
t1 = (0,) * 10 
t2 = (0,) * 100
t3 = (0,) * 1000 
%timeit -n1 -r1 foo(t0)
%timeit -n1 -r1 foo(t1)
%timeit -n1 -r1 foo(t2)
%timeit -n1 -r1 foo(t3)
```

**Comment by apoorvalal** [comment]
reviving this thread since i was experimenting with the rust backend - numba's cold start problem persists and it is a complete non-ssue for the rust backend. another point in favour of making the rust backend default. 

<img width="1056" height="831" alt="Image" src="https://github.com/user-attachments/assets/ed715c24-5561-49e2-b103-0a19ba9f5e45" />

<img width="1003" height="800" alt="Image" src="https://github.com/user-attachments/assets/5d0457dc-a43b-48bb-bf15-1ce796d7a55a" />

**Comment by s3alfisc** [comment]
Yes, that was one of the main hope / motivation to try tbh 😄

**Comment by s3alfisc** [comment]
Btw numba will look even worse if using cluster robust SEs, because these have to be compiled as well ...
