### ISSUE TITLE
negative values in fixed effects crashes kernel 

### ISSUE THREAD

**Issue by apoorvalal** [s3alfisc/pyfixest#425]
A pre-processing step crashes the kernel when the fixed effects have negative values. There's nothing inherently wrong about having negative values in the FEs (since we treat them as categorical and dummy them out); any ideas what might be going on?

MWE: offset the `year` column in the [DID](https://s3alfisc.github.io/pyfixest/difference-in-differences.html) vignette by some fixed number to generate negative values. 

![image](https://github.com/s3alfisc/pyfixest/assets/12086926/bfeab8de-e869-4f1e-a048-a67f7dc7beaf)

**Comment by s3alfisc** [comment]
Hi Apoorva - thanks for reporting! This is a bug I introduced with version 0.19 after reworking the pre-processing / creating of the design matrix. 

The problematic lines are [here](https://github.com/s3alfisc/pyfixest/blob/a5a735fdbb10302234d5ed9e3a62204aab6dced0/pyfixest/estimation/model_matrix_fixest_.py#L442): 

```python
    if pd.api.types.is_integer_dtype(fe) or pd.api.types.is_float_dtype(fe):
        return fe
    else:
        if fe.dtype != "category":
            fe = fe.astype("category")
        res = fe.cat.codes
        res[res == -1] = np.nan
        return res
```
In a nutshell, I thought I could economize on converting variables that are already ints or floats into categoricals (this takes quite a bit of time if the data set is big). But I oversaw that the demeaning algorithm requires not only integers, but positive integers. And likely, I also incorrectly handled floats - if one provides "non-integer float" values, e.g. values of 0.5, the demeaning algo should also crash. 

This should all be fixed with #426 =) 

@contributor-bot please add @apoorvalal for bug
